"""
Generated By: Cursor (Claude Sonnet 4.5)

Project-specific configuration constants for ap-fits-headers.
These are specific to this tool and not shared across projects.
"""

# File pattern constants
INPUT_PATTERN_FITS = r".*\.(fits|fit|FITS|FIT)$"
INPUT_PATTERN_XISF = r".*\.(xisf|XISF)$"
